# Generated by Django 3.2.13 on 2022-08-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20220820_0952'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.user'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.user'),
        ),
    ]
