# Generated by Django 3.2.13 on 2022-08-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=True),
        ),
    ]
