# Generated by Django 3.2.13 on 2022-08-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20220827_1244'),
        ('leads', '0002_auto_20220827_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
