# Generated by Django 3.2.13 on 2022-08-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20220820_0952'),
        ('agents', '0003_auto_20220820_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
